### ISSUE TITLE
Develop backend logic for creating assessment quizzes/surveys. 

### ISSUE THREAD

**Issue by hpmouton** [lighthouse-na/skillharbor#2]
### Description: 
- In this task, the backend logic for generating assessment quizzes or surveys is implemented. This involves designing database schemas, creating APIs or endpoints for CRUD operations on assessments, and integrating validation and error-handling mechanisms.
### Checklist:
- [x] Design database tables or schemas for storing assessment, skills, jcps, and qualifications.
- [x] Develop APIs or endpoints for creating, updating, retrieving, and deleting:
- [x] assessments
- [x] skills
- [x] qualifications
- [x] jcps.
- [x] Implement validation to ensure the integrity of assessment data.
- [x] Handle errors and exceptions gracefully to provide a seamless user experience.

**Comment by aaron-muti-420** [comment]
Creating a Controllers for Assessments 
@hpmouton do I have to create a new Folder or I can add it to the existing Assessments folder `/skillharbor- open/app/Http/Controllers/Assessment`

**Comment by aaron-muti-420** [comment]
i used this command to create a folder named system
`php artisan make:controller System/AssessmentController --resource `

**Comment by hpmouton** [comment]
> i used this command to create a folder named system
> `php artisan make:controller System\\AssessmentController --resource `
> 

Only use one backslash when determining the folder of the controller.

``` bash
php artisan make:controller System/AssessmentController --resource

```
